version: "3"
services:
  db:
    container_name: delivery-app-dev
    image: mysql:8.0.21
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password
networks:
  default:
    name: deliveryApp_net